-- LJT RouteFlow - Final Oracle XE 21c schema
-- Fresh installation script. Run as LJT_ROUTE_FLOW in XEPDB1.
-- Run database/00_preflight.sql first.

SET ECHO ON
SET SQLBLANKLINES ON
SET DEFINE OFF
SET FEEDBACK ON
SET VERIFY OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE TABLE dms_department (
    department_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_code VARCHAR2(30) NOT NULL,
    department_name VARCHAR2(120) NOT NULL,
    status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_dms_department PRIMARY KEY (department_id),
    CONSTRAINT uq_dms_department_code UNIQUE (department_code),
    CONSTRAINT ck_dms_department_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE dms_role (
    role_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    role_code  VARCHAR2(40) NOT NULL,
    role_name  VARCHAR2(120) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_dms_role PRIMARY KEY (role_id),
    CONSTRAINT uq_dms_role_code UNIQUE (role_code)
);

CREATE TABLE dms_user (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR2(80) NOT NULL,
    password_hash VARCHAR2(500) NOT NULL,
    full_name     VARCHAR2(200) NOT NULL,
    email         VARCHAR2(200) NOT NULL,
    department_id NUMBER,
    status        VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_dms_user PRIMARY KEY (user_id),
    CONSTRAINT uq_dms_user_username UNIQUE (username),
    CONSTRAINT uq_dms_user_email UNIQUE (email),
    CONSTRAINT fk_dms_user_department
        FOREIGN KEY (department_id)
        REFERENCES dms_department (department_id),
    CONSTRAINT ck_dms_user_status
        CHECK (status IN ('ACTIVE', 'DISABLED', 'LOCKED'))
);

CREATE TABLE dms_user_role (
    user_id     NUMBER NOT NULL,
    role_id     NUMBER NOT NULL,
    assigned_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_dms_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_dms_user_role_user
        FOREIGN KEY (user_id)
        REFERENCES dms_user (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_dms_user_role_role
        FOREIGN KEY (role_id)
        REFERENCES dms_role (role_id)
        ON DELETE CASCADE
);

CREATE TABLE dms_document (
    document_id               NUMBER GENERATED BY DEFAULT AS IDENTITY,
    document_code             VARCHAR2(60) NOT NULL,
    submission_key            VARCHAR2(64),
    title                     VARCHAR2(250) NOT NULL,
    reference_no              VARCHAR2(120) NOT NULL,
    sender                    VARCHAR2(200) NOT NULL,
    date_received             DATE NOT NULL,
    category                  VARCHAR2(80) NOT NULL,
    priority                  VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL,
    confidential_flag         CHAR(1) DEFAULT 'N' NOT NULL,
    description               VARCHAR2(2000),
    destination_department_id NUMBER NOT NULL,
    boss_id                   NUMBER NOT NULL,
    status                    VARCHAR2(40) DEFAULT 'DRAFT' NOT NULL,
    created_by                NUMBER NOT NULL,
    created_at                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    submitted_at              TIMESTAMP,
    due_date                  DATE,
    approved_at               TIMESTAMP,
    rejection_reason          VARCHAR2(2000),
    updated_at                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_dms_document PRIMARY KEY (document_id),
    CONSTRAINT uq_dms_document_code UNIQUE (document_code),
    CONSTRAINT uq_dms_document_submission UNIQUE (submission_key),
    CONSTRAINT fk_dms_document_department
        FOREIGN KEY (destination_department_id)
        REFERENCES dms_department (department_id),
    CONSTRAINT fk_dms_document_boss
        FOREIGN KEY (boss_id)
        REFERENCES dms_user (user_id),
    CONSTRAINT fk_dms_document_creator
        FOREIGN KEY (created_by)
        REFERENCES dms_user (user_id),
    CONSTRAINT ck_dms_document_priority
        CHECK (priority IN ('NORMAL', 'URGENT')),
    CONSTRAINT ck_dms_document_confidential
        CHECK (confidential_flag IN ('Y', 'N')),
    CONSTRAINT ck_dms_document_status
        CHECK (
            status IN (
                'DRAFT',
                'PENDING_APPROVAL',
                'RETURNED_FOR_CORRECTION',
                'APPROVED',
                'ROUTED',
                'RECALLED',
                'ARCHIVED'
            )
        ),
    CONSTRAINT ck_dms_document_pending_dates
        CHECK (
            status <> 'PENDING_APPROVAL'
            OR (submitted_at IS NOT NULL AND due_date IS NOT NULL)
        ),
    CONSTRAINT ck_dms_document_return_reason
        CHECK (
            status <> 'RETURNED_FOR_CORRECTION'
            OR rejection_reason IS NOT NULL
        )
);

CREATE TABLE dms_document_file (
    file_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    document_id   NUMBER NOT NULL,
    original_name VARCHAR2(255) NOT NULL,
    storage_name  VARCHAR2(255) NOT NULL,
    storage_path  VARCHAR2(1000) NOT NULL,
    mime_type     VARCHAR2(150),
    file_size     NUMBER NOT NULL,
    primary_flag  CHAR(1) DEFAULT 'N' NOT NULL,
    uploaded_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_dms_document_file PRIMARY KEY (file_id),
    CONSTRAINT fk_dms_file_document
        FOREIGN KEY (document_id)
        REFERENCES dms_document (document_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_dms_file_primary
        CHECK (primary_flag IN ('Y', 'N')),
    CONSTRAINT ck_dms_file_size
        CHECK (file_size >= 0)
);

CREATE TABLE dms_approval (
    approval_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    document_id           NUMBER NOT NULL,
    approver_id           NUMBER NOT NULL,
    decision              VARCHAR2(20) NOT NULL,
    remarks               VARCHAR2(2000),
    previous_department_id NUMBER,
    new_department_id     NUMBER,
    decision_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_dms_approval PRIMARY KEY (approval_id),
    CONSTRAINT fk_dms_approval_document
        FOREIGN KEY (document_id)
        REFERENCES dms_document (document_id),
    CONSTRAINT fk_dms_approval_user
        FOREIGN KEY (approver_id)
        REFERENCES dms_user (user_id),
    CONSTRAINT fk_dms_approval_old_department
        FOREIGN KEY (previous_department_id)
        REFERENCES dms_department (department_id),
    CONSTRAINT fk_dms_approval_new_department
        FOREIGN KEY (new_department_id)
        REFERENCES dms_department (department_id),
    CONSTRAINT ck_dms_approval_decision
        CHECK (decision IN ('APPROVE', 'REJECT')),
    CONSTRAINT ck_dms_approval_reject_reason
        CHECK (decision <> 'REJECT' OR remarks IS NOT NULL)
);

CREATE TABLE dms_document_history (
    history_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    document_id NUMBER NOT NULL,
    user_id     NUMBER NOT NULL,
    action      VARCHAR2(80) NOT NULL,
    old_value   VARCHAR2(1000),
    new_value   VARCHAR2(1000),
    remarks     VARCHAR2(2000),
    action_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_dms_document_history PRIMARY KEY (history_id),
    CONSTRAINT fk_dms_history_document
        FOREIGN KEY (document_id)
        REFERENCES dms_document (document_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_dms_history_user
        FOREIGN KEY (user_id)
        REFERENCES dms_user (user_id)
);

CREATE TABLE dms_notification (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    recipient_id    NUMBER NOT NULL,
    type            VARCHAR2(60) NOT NULL,
    message         VARCHAR2(1000) NOT NULL,
    document_id     NUMBER,
    read_flag       CHAR(1) DEFAULT 'N' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    read_at         TIMESTAMP,

    CONSTRAINT pk_dms_notification PRIMARY KEY (notification_id),
    CONSTRAINT fk_dms_notification_recipient
        FOREIGN KEY (recipient_id)
        REFERENCES dms_user (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_dms_notification_document
        FOREIGN KEY (document_id)
        REFERENCES dms_document (document_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_dms_notification_read
        CHECK (read_flag IN ('Y', 'N')),
    CONSTRAINT ck_dms_notification_read_time
        CHECK (
            (read_flag = 'N' AND read_at IS NULL)
            OR read_flag = 'Y'
        )
);

CREATE TABLE dms_role_change_request (
    request_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id            NUMBER NOT NULL,
    current_role_code  VARCHAR2(40),
    requested_role_code VARCHAR2(40) NOT NULL,
    requested_by       NUMBER NOT NULL,
    approved_by        NUMBER,
    status             VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    remarks            VARCHAR2(1000),
    requested_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    decided_at         TIMESTAMP,

    CONSTRAINT pk_dms_role_request PRIMARY KEY (request_id),
    CONSTRAINT fk_dms_role_request_user
        FOREIGN KEY (user_id)
        REFERENCES dms_user (user_id),
    CONSTRAINT fk_dms_role_request_requested_by
        FOREIGN KEY (requested_by)
        REFERENCES dms_user (user_id),
    CONSTRAINT fk_dms_role_request_approved_by
        FOREIGN KEY (approved_by)
        REFERENCES dms_user (user_id),
    CONSTRAINT ck_dms_role_request_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_dms_role_request_decision
        CHECK (
            status = 'PENDING'
            OR decided_at IS NOT NULL
        )
);

-- Case-insensitive uniqueness aligned with application login logic.
CREATE UNIQUE INDEX uq_dms_user_username_ci
    ON dms_user (LOWER(username));

CREATE UNIQUE INDEX uq_dms_user_email_ci
    ON dms_user (LOWER(email));

CREATE UNIQUE INDEX uq_dms_department_code_ci
    ON dms_department (LOWER(department_code));

CREATE UNIQUE INDEX uq_dms_role_code_ci
    ON dms_role (LOWER(role_code));

-- A document may have only one primary file.
CREATE UNIQUE INDEX uq_dms_file_one_primary
    ON dms_document_file (
        CASE WHEN primary_flag = 'Y' THEN document_id END
    );

-- Prevent two identical pending role requests for one user.
CREATE UNIQUE INDEX uq_dms_pending_role_request
    ON dms_role_change_request (
        CASE WHEN status = 'PENDING' THEN user_id END,
        CASE WHEN status = 'PENDING' THEN requested_role_code END
    );

CREATE INDEX idx_dms_document_status
    ON dms_document (status);

CREATE INDEX idx_dms_document_boss
    ON dms_document (boss_id, status);

CREATE INDEX idx_dms_document_destination
    ON dms_document (destination_department_id, status);

CREATE INDEX idx_dms_document_creator
    ON dms_document (created_by, created_at);

CREATE INDEX idx_dms_document_reference
    ON dms_document (reference_no);

CREATE INDEX idx_dms_document_file_document
    ON dms_document_file (document_id, primary_flag);

CREATE INDEX idx_dms_approval_document
    ON dms_approval (document_id, decision_at);

CREATE INDEX idx_dms_notification_user
    ON dms_notification (recipient_id, read_flag, created_at);

CREATE INDEX idx_dms_history_document
    ON dms_document_history (document_id, action_at);

CREATE INDEX idx_dms_role_request_status
    ON dms_role_change_request (status, requested_at);

CREATE OR REPLACE TRIGGER trg_dms_user_updated_at
BEFORE UPDATE ON dms_user
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_dms_document_updated_at
BEFORE UPDATE ON dms_document
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

COMMIT;

PROMPT LJT RouteFlow schema created successfully.
