-- LJT RouteFlow - Oracle Database 21c schema
-- Run as the application schema owner, not SYS/SYSTEM.

CREATE TABLE dms_department (
  department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_code VARCHAR2(30) NOT NULL UNIQUE,
  department_name VARCHAR2(120) NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE dms_role (
  role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_code VARCHAR2(40) NOT NULL UNIQUE,
  role_name VARCHAR2(120) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE dms_user (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(80) NOT NULL UNIQUE,
  password_hash VARCHAR2(500) NOT NULL,
  full_name VARCHAR2(200) NOT NULL,
  email VARCHAR2(200) NOT NULL UNIQUE,
  department_id NUMBER NULL REFERENCES dms_department(department_id),
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE','DISABLED','LOCKED')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE dms_user_role (
  user_id NUMBER NOT NULL REFERENCES dms_user(user_id) ON DELETE CASCADE,
  role_id NUMBER NOT NULL REFERENCES dms_role(role_id) ON DELETE CASCADE,
  assigned_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE dms_document (
  document_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_code VARCHAR2(60) NOT NULL UNIQUE,
  title VARCHAR2(250) NOT NULL,
  reference_no VARCHAR2(120) NOT NULL,
  sender VARCHAR2(200) NOT NULL,
  date_received DATE NOT NULL,
  category VARCHAR2(80) NOT NULL,
  priority VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL CHECK (priority IN ('NORMAL','URGENT')),
  confidential_flag CHAR(1) DEFAULT 'N' NOT NULL CHECK (confidential_flag IN ('Y','N')),
  description VARCHAR2(2000),
  destination_department_id NUMBER NOT NULL REFERENCES dms_department(department_id),
  boss_id NUMBER NOT NULL REFERENCES dms_user(user_id),
  status VARCHAR2(40) DEFAULT 'DRAFT' NOT NULL CHECK (status IN ('DRAFT','PENDING_APPROVAL','RETURNED_FOR_CORRECTION','APPROVED','ROUTED','RECALLED','ARCHIVED')),
  created_by NUMBER NOT NULL REFERENCES dms_user(user_id),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  submitted_at TIMESTAMP,
  due_date DATE,
  approved_at TIMESTAMP,
  rejection_reason VARCHAR2(2000),
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE dms_document_file (
  file_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id NUMBER NOT NULL REFERENCES dms_document(document_id) ON DELETE CASCADE,
  original_name VARCHAR2(255) NOT NULL,
  storage_name VARCHAR2(255) NOT NULL,
  storage_path VARCHAR2(1000) NOT NULL,
  mime_type VARCHAR2(150),
  file_size NUMBER NOT NULL,
  primary_flag CHAR(1) DEFAULT 'N' NOT NULL CHECK (primary_flag IN ('Y','N')),
  uploaded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE dms_approval (
  approval_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id NUMBER NOT NULL REFERENCES dms_document(document_id),
  approver_id NUMBER NOT NULL REFERENCES dms_user(user_id),
  decision VARCHAR2(20) NOT NULL CHECK (decision IN ('APPROVE','REJECT')),
  remarks VARCHAR2(2000),
  previous_department_id NUMBER REFERENCES dms_department(department_id),
  new_department_id NUMBER REFERENCES dms_department(department_id),
  decision_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE dms_document_history (
  history_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id NUMBER NOT NULL REFERENCES dms_document(document_id) ON DELETE CASCADE,
  user_id NUMBER NOT NULL REFERENCES dms_user(user_id),
  action VARCHAR2(80) NOT NULL,
  old_value VARCHAR2(1000),
  new_value VARCHAR2(1000),
  remarks VARCHAR2(2000),
  action_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE dms_notification (
  notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id NUMBER NOT NULL REFERENCES dms_user(user_id) ON DELETE CASCADE,
  type VARCHAR2(60) NOT NULL,
  message VARCHAR2(1000) NOT NULL,
  document_id NUMBER REFERENCES dms_document(document_id) ON DELETE CASCADE,
  read_flag CHAR(1) DEFAULT 'N' NOT NULL CHECK (read_flag IN ('Y','N')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  read_at TIMESTAMP
);

CREATE TABLE dms_role_change_request (
  request_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL REFERENCES dms_user(user_id),
  current_role_code VARCHAR2(40),
  requested_role_code VARCHAR2(40) NOT NULL,
  requested_by NUMBER NOT NULL REFERENCES dms_user(user_id),
  approved_by NUMBER REFERENCES dms_user(user_id),
  status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING','APPROVED','REJECTED','CANCELLED')),
  remarks VARCHAR2(1000),
  requested_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  decided_at TIMESTAMP
);

CREATE INDEX idx_dms_document_status ON dms_document(status);
CREATE INDEX idx_dms_document_boss ON dms_document(boss_id,status);
CREATE INDEX idx_dms_document_destination ON dms_document(destination_department_id,status);
CREATE INDEX idx_dms_document_creator ON dms_document(created_by,created_at);
CREATE INDEX idx_dms_notification_user ON dms_notification(recipient_id,read_flag,created_at);
CREATE INDEX idx_dms_history_document ON dms_document_history(document_id,action_at);

COMMIT;
